# Inherit the settings from mkdocs-base.yml using Configuration Inheritance
# https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance

INHERIT: mkdocs-base.yml

# Theme
theme:
  icon:
    repo: fontawesome/brands/bitbucket